### ISSUE TITLE
The number of parameters has been reduced, but the calculation speed has not improved

### ISSUE THREAD

**Issue by KobeChe** [google/TensorNetwork#807] opened 2020-09-02 06:19 UTC
```python:
class TNLayer(keras.layers.Layer):
    def __init__(self):
        super(TNLayer, self).__init__()
        self.a_var=tf.Variable(tf.random.normal(shape=[32,32,2],stddev=1.0/32.0),name='s',trainable=True)
        self.b_var=tf.Variable(tf.random.normal(shape=[32,32,2],stddev=1.0/32.0),name='s',trainable=True)
        self.bias=tf.Variable(tf.Variable(tf.zeros(shape=[32,32])),name='bias',trainable=True)
    def call(self, inputs):
        def f(input_vec,a_vars,b_vars,bias):
            input_vec=tf.reshape(input_vec,shape=[32,32])
            a=tn.Node(tensor=a_vars,backend='tensorflow')
            b=tn.Node(tensor=b_vars,backend='tensorflow')
            x_node=tn.Node(tensor=input_vec,backend='tensorflow')
            a[1] ^ x_node[0]
            b[1] ^ x_node[1]
            a[2] ^ b[2]
            c=a @ x_node
            result=(c@b).tensor
            return result+bias
        result=tf.vectorized_map(lambda input_vector:f(input_vector,self.a_var,self.b_var,self.bias),inputs)
        return tf.nn.relu(tf.reshape(result,[-1,1024]))
fc_model_TN = keras.models.Sequential(
        [
            keras.layers.Input(shape=(2,)),
            keras.layers.Dense(1024, activation=tf.nn.swish),
            TNLayer(),
            keras.layers.Dense(1, activation=None)
        ]
    )
fc_model=keras.models.Sequential(
    [
        keras.layers.Input(shape=(2,)),
        keras.layers.Dense(1024,activation=tf.nn.swish),
        keras.layers.Dense(1024,activation=tf.nn.swish),
        keras.layers.Dense(1,activation=None)
    ]
)

```
**Why fc_model_TN has fewer parameters than fc_model, but fc_model_TN is not as fast as fc_model**

**Comment by mganahl** [comment] 2020-09-02 08:43
Hi @KobeChe, thanks for the issue.  It looks like you are hitting spurious retracing in tensorflow.  The problem seems caused by your implementation of the `call`. We can't really do anything about this, since this is a tensorflow issue. However, I took a quick look, and maybe the following fixes your problem:

Rather than defining `f` and the vectorization call within `call`, you should move both in `__init__`. Unfortunately I'm not familiar with the interior workings of `vectorized_map`, but the following alternative implementation at least doesn't trigger any spurious retracing and is as fast as the `fc_model`. 
``` python 

class TNLayer(keras.layers.Layer):
    def __init__(self):
        super(TNLayer, self).__init__()
        self.a_var=tf.Variable(tf.random.normal(shape=[32,32,2],stddev=1.0/32.0),name='s',trainable=False)
        self.b_var=tf.Variable(tf.random.normal(shape=[32,32,2],stddev=1.0/32.0),name='b',trainable=False)
        self.bias=tf.Variable(tf.Variable(tf.zeros(shape=[32,32])),name='bias',trainable=True)
        def wrapper(input_vector):
            input_vec=tf.reshape(input_vector,shape=[32,32])
            a=tn.Node(tensor=self.a_var,backend='tensorflow')
            b=tn.Node(tensor=self.b_var,backend='tensorflow')
            x_node=tn.Node(tensor=input_vec,backend='tensorflow')
            a[1] ^ x_node[0]
            b[1] ^ x_node[1]
            a[2] ^ b[2]
            c=a @ x_node
            result=(c@b).tensor
            return result+self.bias
        def vectorized_wrapper(inp):
            return tf.vectorized_map(wrapper, inp)
        self.vectorized_wrapper = tf.function(vectorized_wrapper)        
    def call(self, inputs):
        return self.vectorized_wrapper(inputs)
```
Let me know if this was helpful!

**Comment by mganahl** [comment] 2020-09-02 13:13
I'll close this because it's not directly related to TensorNetwork

**Closed by mganahl** 2020-09-02 13:13 UTC
