### ISSUE TITLE
__init__() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by ammonite** [google/TensorNetwork#121] opened 2019-06-21 02:40 UTC
My environment: Ubuntu 18.04, tensorflow=='2.0.0-beta0'
Code from arxiv.1905.1330:
```
net = tensornetwork.TensorNetwork()
a = net.add_node(tf.ones(2))
b = net.add_node(tf.ones(2))
edge = net.connect(a[0], b[0])
c = net.contract(edge)
print(c.get_tensor().numpy()) # Should print 2.0
```
Error message:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-cb4097656450> in <module>
      3 b = net.add_node(tf.ones(2))
      4 edge = net.connect(a[0], b[0])
----> 5 c = net.contract(edge)
      6 print(c.get_tensor().numpy()) # Should print 2.0
~/miniconda3/lib/python3.6/site-packages/tensornetwork/network.py in contract(self, edge, name)
    381       return self._contract_trace(edge, name)
    382     new_tensor = self.backend.tensordot(edge.node1.tensor, edge.node2.tensor,
--> 383                                         [[edge.axis1], [edge.axis2]])
    384     new_node = self.add_node(new_tensor, name)
    385     self._remove_edges(set([edge]), edge.node1, edge.node2, new_node)
~/miniconda3/lib/python3.6/site-packages/tensornetwork/backends/tensorflow/tensorflow_backend.py in tensordot(self, a, b, axes)
     41 
     42   def tensordot(self, a: Tensor, b: Tensor, axes: Sequence[Sequence[int]]):
---> 43     return self.tensordot2.tensordot(a, b, axes)
     44 
     45   def reshape(self, tensor: Tensor, shape: Tensor):
~/miniconda3/lib/python3.6/site-packages/tensornetwork/backends/tensorflow/tensordot2.py in tensordot(a, b, axes, name)
    227     return axes[0], axes[1]
    228 
--> 229   with tf.name_scope(name, "Tensordot", [a, b, axes]) as _name:
    230     a = tf.convert_to_tensor(a, name="a")
    231     b = tf.convert_to_tensor(b, name="b")
TypeError: __init__() takes 2 positional arguments but 4 were given
```

* Edited by Thenerdstation for formatting.

**Comment by Thenerdstation** [comment] 2019-06-21 02:55
That's very strange. Looks like it might be an issue with the tensorflow version. (we've only tested with 1.13). Let me see if I can replicate this locally.

**Comment by Thenerdstation** [comment] 2019-06-21 03:03
Yep, I hit it. This is definitely an incompatibility issue between TF1 and TF2.

**Comment by Thenerdstation** [comment] 2019-06-21 03:39
Yikes, there are a lot of issues with the beta version of TF2. `tf.trace` and `tf.svd` aliases are just flat out missing, and the `tf.name_scope` seems to have incompatible APIs. 

https://github.com/google/TensorNetwork/pull/122 fixes most of the incompatibility under the `tensornetwork/`, but seeing how this is a beta library that will likely go through a lot of breaking changes, we aren't going to try to support it until TF 2.0 is fully released.

**Comment by Thenerdstation** [comment] 2019-06-21 03:40
Once this PR is approved and merged, we'll release a version 0.0.4 of tensornetwork sometime tomorrow.

**Comment by Thenerdstation** [comment] 2019-06-21 21:06
PR is in, we'll drop 0.0.4 soon.

**Closed by Thenerdstation** 2019-06-21 21:06 UTC

**Comment by Thenerdstation** [comment] 2019-06-21 23:44
0.0.4 is out now.

**Comment by anjugopinath** [comment] 2020-11-20 21:59
Hi , I am getting this error. My conda environment has TF 1.15.0. How can I fix this? Thank You.

**Comment by mganahl** [comment] 2020-11-20 22:55
thanks @anjugopinath for the issue. In fact, using the `tn.TensorNetwork` object is deprecated for a while now and is no longer supported. Which version of `tensornetwork` are you using?
Could you provide a minimal working code example that reproduces the error? Thanks!

**Comment by anjugopinath** [comment] 2020-11-20 23:23
hi @mganahl Thank You so much for replying.
Line number 35 of this code is throwing the error : https://github.com/shreyashampali/HOnnotate/blob/master/optimization/object/batch_object.py
This code has been tested on tensorflow 1.12. My conda environment has tensorflow 1.15

**Comment by mganahl** [comment] 2020-11-23 20:12
It seems that this code is not using `tensornetwork`. Are you perhaps confusing it with `tensorflow`?
